package com.pojos;
// Generated 8 août 2016 01:05:34 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TUsers generated by hbm2java
 */
@Entity
@Table(name="COMPTE" ,schema="DEMO")
public class Compte  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal compteId;
     private String nom;
     private String prenoms;
     private String dateNaissance;
     private String lieuNaissance;
     private String adresse;
     private String numero;
     private String typeService;
     private String typePiece;
     private String piece;
     private String typeCompte;
     private String statut;
     private String systemSourceCode;
     private String compteContribuable;
     

    public Compte() {
    }
  

	public Compte(BigDecimal compteId, String nom, String prenoms, String dateNaissance, String lieuNaissance,
			String adresse, String numero, String typeService, String typePiece, String piece, String typeCompte,
			String statut, String systemSourceCode) {
		super();
		this.compteId = compteId;
		this.nom = nom;
		this.prenoms = prenoms;
		this.dateNaissance = dateNaissance;
		this.lieuNaissance = lieuNaissance;
		this.adresse = adresse;
		this.numero = numero;
		this.typeService = typeService;
		this.typePiece = typePiece;
		this.piece = piece;
		this.typeCompte = typeCompte;
		this.statut = statut;
		this.systemSourceCode = systemSourceCode;
	}


	@Id 
	@Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
	public BigDecimal getCompteId() {
		return compteId;
	}


	public void setCompteId(BigDecimal compteId) {
		this.compteId = compteId;
	}


	public String getNom() {
		return nom;
	}


	public void setNom(String nom) {
		this.nom = nom;
	}


	public String getPrenoms() {
		return prenoms;
	}


	public void setPrenoms(String prenoms) {
		this.prenoms = prenoms;
	}

	@Column(name="DATE_NAISSANCE", length=40)
	public String getDateNaissance() {
		return dateNaissance;
	}


	public void setDateNaissance(String dateNaissance) {
		this.dateNaissance = dateNaissance;
	}

	@Column(name="LIEU_NAISSANCE", length=40)
	public String getLieuNaissance() {
		return lieuNaissance;
	}


	public void setLieuNaissance(String lieuNaissance) {
		this.lieuNaissance = lieuNaissance;
	}


	public String getAdresse() {
		return adresse;
	}


	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}


	public String getNumero() {
		return numero;
	}


	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Column(name="TYPE_SERVICE", length=40)
	public String getTypeService() {
		return typeService;
	}


	public void setTypeService(String typeService) {
		this.typeService = typeService;
	}


	public String getTypePiece() {
		return typePiece;
	}


	public void setTypePiece(String typePiece) {
		this.typePiece = typePiece;
	}

	@Column(name="PIECE", length=40)
	public String getPiece() {
		return piece;
	}

	
	public void setPiece(String piece) {
		this.piece = piece;
	}

	@Column(name="TYPE_COMPTE")
	public String getTypeCompte() {
		return typeCompte;
	}


	public void setTypeCompte(String typeCompte) {
		this.typeCompte = typeCompte;
	}

	@Column(name="STATUT")
	public String getStatut() {
		return statut;
	}


	public void setStatut(String statut) {
		this.statut = statut;
	}

	@Column(name="SYSTEM_SOURCE_CODE")
	public String getSystemSourceCode() {
		return systemSourceCode;
	}


	public void setSystemSourceCode(String systemSourceCode) {
		this.systemSourceCode = systemSourceCode;
	}

	@Column(name="COMPTE_CONTRI")
	public String getCompteContribuable() {
		return compteContribuable;
	}


	public void setCompteContribuable(String compteContribuable) {
		this.compteContribuable = compteContribuable;
	}
	
	
	
    
}


