package com.pojos;
// Generated 16 août 2016 00:01:08 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClientUniqueOcit generated by hbm2java
 */
@Entity
@Table(name="CLIENT_UNIQUE_OCIT"
    ,schema="DEMO"
)
public class CUO  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String phone;
     private BigDecimal masterId;
     private Date dateCreation;
     private Date dateCessation;
     private String typeMatch;
     private BigDecimal typeservice;

    public CUO() {
    }

	
    public CUO(String phone, BigDecimal masterId) {
        this.phone = phone;
        this.masterId = masterId;
    }
    public CUO(String phone, BigDecimal masterId, Date dateCreation, Date dateCessation, String typeMatch, BigDecimal typeservice) {
       this.phone = phone;
       this.masterId = masterId;
       this.dateCreation = dateCreation;
       this.dateCessation = dateCessation;
       this.typeMatch = typeMatch;
       this.typeservice = typeservice;
    }
   
     @Id 

    
    @Column(name="PHONE", unique=true, nullable=false, length=20)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="MASTER_ID", nullable=false, precision=22, scale=0)
    public BigDecimal getMasterId() {
        return this.masterId;
    }
    
    public void setMasterId(BigDecimal masterId) {
        this.masterId = masterId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_CREATION", length=7)
    public Date getDateCreation() {
        return this.dateCreation;
    }
    
    public void setDateCreation(Date dateCreation) {
        this.dateCreation = dateCreation;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_CESSATION", length=7)
    public Date getDateCessation() {
        return this.dateCessation;
    }
    
    public void setDateCessation(Date dateCessation) {
        this.dateCessation = dateCessation;
    }

    
    @Column(name="TYPE_MATCH", length=20)
    public String getTypeMatch() {
        return this.typeMatch;
    }
    
    public void setTypeMatch(String typeMatch) {
        this.typeMatch = typeMatch;
    }

    
    @Column(name="TYPESERVICE", precision=22, scale=0)
    public BigDecimal getTypeservice() {
        return this.typeservice;
    }
    
    public void setTypeservice(BigDecimal typeservice) {
        this.typeservice = typeservice;
    }




}


