package com.pojos;
// Generated 8 août 2016 01:05:34 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TUsers generated by hbm2java
 */
@Entity
@Table(name="T_USERS" ,schema="DEMO")
public class TUsers  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal id;
     private String nom;
     private String prenoms;
     private String lieuNaissance;
     private String adresse;
     private String telFixe;
     private String telMobile;
     private String email;
     private String aviso;
     private String orangeMoney;
     private String service;
     private String typeService;
     private String dateNaissance;

    public TUsers() {
    }

	
    public TUsers(BigDecimal id) {
        this.id = id;
    }
    public TUsers(BigDecimal id, String nom, String prenoms, String lieuNaissance, String adresse, String telFixe, String telMobile, String email, String aviso, String orangeMoney, String service, String typeService, String dateNaissance) {
       this.id = id;
       this.nom = nom;
       this.prenoms = prenoms;
       this.lieuNaissance = lieuNaissance;
       this.adresse = adresse;
       this.telFixe = telFixe;
       this.telMobile = telMobile;
       this.email = email;
       this.aviso = aviso;
       this.orangeMoney = orangeMoney;
       this.service = service;
       this.typeService = typeService;
       this.dateNaissance = dateNaissance;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

    
    @Column(name="NOM", length=20)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="PRENOMS", length=40)
    public String getPrenoms() {
        return this.prenoms;
    }
    
    public void setPrenoms(String prenoms) {
        this.prenoms = prenoms;
    }

    
    @Column(name="LIEU_NAISSANCE", length=40)
    public String getLieuNaissance() {
        return this.lieuNaissance;
    }
    
    public void setLieuNaissance(String lieuNaissance) {
        this.lieuNaissance = lieuNaissance;
    }

    
    @Column(name="ADRESSE", length=40)
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }

    
    @Column(name="TEL_FIXE", length=10)
    public String getTelFixe() {
        return this.telFixe;
    }
    
    public void setTelFixe(String telFixe) {
        this.telFixe = telFixe;
    }

    
    @Column(name="TEL_MOBILE", length=10)
    public String getTelMobile() {
        return this.telMobile;
    }
    
    public void setTelMobile(String telMobile) {
        this.telMobile = telMobile;
    }

    
    @Column(name="EMAIL", length=40)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="AVISO", length=40)
    public String getAviso() {
        return this.aviso;
    }
    
    public void setAviso(String aviso) {
        this.aviso = aviso;
    }

    
    @Column(name="ORANGE_MONEY", length=40)
    public String getOrangeMoney() {
        return this.orangeMoney;
    }
    
    public void setOrangeMoney(String orangeMoney) {
        this.orangeMoney = orangeMoney;
    }

    
    @Column(name="SERVICE", length=40)
    public String getService() {
        return this.service;
    }
    
    public void setService(String service) {
        this.service = service;
    }

    
    @Column(name="TYPE_SERVICE", length=40)
    public String getTypeService() {
        return this.typeService;
    }
    
    public void setTypeService(String typeService) {
        this.typeService = typeService;
    }

    
    @Column(name="DATE_NAISSANCE", length=50)
    public String getDateNaissance() {
        return this.dateNaissance;
    }
    
    public void setDateNaissance(String dateNaissance) {
        this.dateNaissance = dateNaissance;
    }




}


